---
- name: Configure CORE BABA DHCP
  hosts: baba
  gather_facts: false

  tasks:
    - name: Configure DHCP excluded addresses
      ios_config:
        lines:
          - ip dhcp excluded-address 10.~~.1.1 10.~~.1.100
          - ip dhcp excluded-address 10.~~.10.1 10.~~.10.100
          - ip dhcp excluded-address 10.~~.50.1 10.~~.50.100
          - ip dhcp excluded-address 10.~~.100.1 10.~~.100.100

    - name: Configure MGMTDATA DHCP pool
      ios_config:
        parents:
          - ip dhcp pool MGMTDATA
        lines:
          - network 10.~~.1.0 255.255.255.0
          - default-router 10.~~.1.4
          - domain-name MGMTDATA.COM
          - dns-server 10.~~.1.10

    - name: Configure WIFIDATA DHCP pool
      ios_config:
        parents:
          - ip dhcp pool WIFIDATA
        lines:
          - network 10.~~.10.0 255.255.255.0
          - default-router 10.~~.10.4
          - domain-name WIFIDATA.COM
          - dns-server 10.~~.1.10

    - name: Configure IPCCTV DHCP pool
      ios_config:
        parents:
          - ip dhcp pool IPCCTV
        lines:
          - network 10.~~.50.0 255.255.255.0
          - default-router 10.~~.50.4
          - domain-name IPCCTV.COM
          - dns-server 10.~~.1.10

    - name: Configure VOICEVLAN DHCP pool
      ios_config:
        parents:
          - ip dhcp pool VOICEVLAN
        lines:
          - network 10.~~.100.0 255.255.255.0
          - default-router 10.~~.100.4
          - domain-name VOICEVLAN.COM
          - dns-server 10.~~.1.10
          - option 150 ip 10.~~.100.8

    - name: Save configuration
      ios_config:
        save_when: modified
