---
- name: Show Cisco Version
  hosts: cisco
  gather_facts: no

  tasks:
    - name: Run show version
      ios_command:
        commands:
          - show version
      register: output

    - name: Display output
      debug:
        var: output.stdout_lines
